// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6LPu3od6Yl_s6vPOk4L76XGl2MlV6OKk',
    appId: '1:474591405816:web:797e3150efb189f1b13d0d',
    messagingSenderId: '474591405816',
    projectId: 'otp-verify-4132d',
    authDomain: 'otp-verify-4132d.firebaseapp.com',
    storageBucket: 'otp-verify-4132d.appspot.com',
    measurementId: 'G-FJ16ER8TD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8gzrxDvHRVTMRI9PUAag9XOVxf9Mda8s',
    appId: '1:474591405816:android:36853f147531784cb13d0d',
    messagingSenderId: '474591405816',
    projectId: 'otp-verify-4132d',
    storageBucket: 'otp-verify-4132d.appspot.com',
  );
}
